module.exports = {
  PORT: process.env.PORT || 4000,
  JWT_SECRET: process.env.JWT_SECRET || "secret_key",
  COIN_PAIRS: [
    "btcusdt",
    "ethusdt",
    "xrpusdt",
    "solusdt",
    "hbarusdt",
    "nearusdt",
    "tiausdt",
    "tonusdt",
    "enausdt",
    "cakeusdt",
    "seiusdt",
    "kaitousdt",
    "berausdt",
  ],
  INITIAL_PRICES: {
    BTC: 0,
    ETH: 0,
    XRP: 0,
    SOL: 0,
    HBAR: 0,
    NEAR: 0,
    TIA: 0,
    TON: 0,
    ENA: 0,
    CAKE: 0,
    SEI: 0,
    KAITO: 0,
    BERA: 0,
  },
};
